apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-xle0
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-xle0
    app.kubernetes.io/part-of: ci1t-830-0020-app
  name: devfile-sample-xle0
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-xle0
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-xle0
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-830-0020-tenant/ci1t-830-0020-app/devfile-sample-xle0@sha256:e336544dfa822fe93024936d8c8621a4255a050226ccb76a45be1398113d5856
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
